apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: model-registry-grpc
spec:
  gateways:
    - kubeflow-gateway-grpc
  hosts:
    - model-registry-service-grpc.apps.rosa.rareddy-rosa2.h9lo.p3.openshiftapps.com
  http:
  - match:
    - uri:
        prefix: /ml_metadata.MetadataStoreService
    route:
    - destination:
        host: model-registry-service.kubeflow.svc.cluster.local
        port:
          number: 9090
