apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: model-registry-service
spec:
  action: CUSTOM
  provider:
    name: "opendatahub-auth-provider"
  selector:
    matchLabels:
      component: model-registry-server
  rules:
  - {}
