apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- istio-authorization-policy.yaml
- istio-authorization-policy-db.yaml
- destination-rule.yaml
- virtual-service.yaml
- gateway.yaml