apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: model-registry-users
  namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: registry-user-default
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: model-registry-users