apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: model-registry
spec:
  gateways:
    - kubeflow-gateway
  hosts:
    - model-registry-service.apps.rosa.rareddy-rosa2.h9lo.p3.openshiftapps.com
    - model-registry-service
  http:
  - match:
    - uri:
        extract: /api
    route:
    - destination:
        host: model-registry-service
        port:
          number: 8080
 # tcp:
 # - match:
 #     - port: 9090
 #   route:
 #     - destination:
 #         host: model-registry-service
 #         port:
 #           number: 9090
