apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: model-registry-rest-vsvc-incluster
spec:
  hosts:
    - model-registry-service.kubeflow.svc.cluster.local
  tcp:
  - match:
    - port: 8080
    route:
    - destination:
        host: model-registry-service.kubeflow.svc.cluster.local
        port:
          number: 8080
 # tcp:
 # - match:
 #     - port: 9090
 #   route:
 #     - destination:
 #         host: model-registry-service
 #         port:
 #           number: 9090
